#!/bin/bash
# Alibaba Cloud CLI Script to Create VPC and vSwitches
# Generated by ipcalc.cloud

# ========================================
# Variables
# ========================================
REGION="cn-hangzhou"
VPC_NAME="myproject-vpc"
VPC_CIDR="{{vpcCidr}}"

# ========================================
# Create VPC
# ========================================
echo "Creating VPC..."
VPC_ID=$(aliyun vpc CreateVpc \
  --RegionId "${REGION}" \
  --CidrBlock "${VPC_CIDR}" \
  --VpcName "${VPC_NAME}" \
  --Description "VPC created by IP Calculator" \
  2>/dev/null | python3 -c "
import json,sys
try:
  s=sys.stdin.read(); print(json.loads(s).get('VpcId','') if s.strip() else '')
except: print('')
")

if [ -z "${VPC_ID}" ]; then
  echo "Error: Failed to create VPC"
  exit 1
fi
echo "VPC created with ID: ${VPC_ID}"
echo "Waiting for VPC to be available..."
sleep 5

# ========================================
# Create vSwitches
# ========================================
{{vSwitchCreation}}
echo "Alibaba Cloud VPC and vSwitches created successfully!"

# ========================================
# Display VPC and vSwitches
# ========================================
echo "VPC Details:"
aliyun vpc DescribeVpcAttribute --VpcId "${VPC_ID}"

echo "vSwitch Details:"
aliyun vpc DescribeVSwitches --VpcId "${VPC_ID}"
