# Terraform Configuration for Alibaba Cloud VPC and vSwitches
# Generated by ipcalc.cloud

# ========================================
# Provider Configuration
# ========================================

terraform {
  required_providers {
    alicloud = {
      source  = "aliyun/alicloud"
      version = "~> 1.0"
    }
  }
}

provider "alicloud" {
  region = var.region
}

# ========================================
# Variables
# ========================================

variable "region" {
  description = "Alibaba Cloud Region"
  type        = string
  default     = "cn-hangzhou"
}

variable "vpc_name" {
  description = "Name of the VPC"
  type        = string
  default     = "myproject-vpc"
}

variable "vpc_cidr" {
  description = "CIDR block for the VPC"
  type        = string
  default     = "{{vpcCidr}}"
}

{{vSwitchVariables}}
# ========================================
# VPC
# ========================================

resource "alicloud_vpc" "vpc" {
  vpc_name    = var.vpc_name
  cidr_block  = var.vpc_cidr
  description = "VPC created by Terraform"

  tags = {
    Environment = "Production"
    ManagedBy   = "Terraform"
  }
}

# ========================================
# vSwitches
# ========================================

{{vSwitchResources}}
# ========================================
# Security Group (Example)
# ========================================

resource "alicloud_security_group" "sg" {
  name        = "${var.vpc_name}-sg"
  description = "Security group for ${var.vpc_name}"
  vpc_id      = alicloud_vpc.vpc.id

  tags = {
    Environment = "Production"
    ManagedBy   = "Terraform"
  }
}

# Allow internal communication
resource "alicloud_security_group_rule" "allow_internal" {
  type              = "ingress"
  ip_protocol       = "all"
  policy            = "accept"
  port_range        = "-1/-1"
  security_group_id = alicloud_security_group.sg.id
  cidr_ip           = var.vpc_cidr
}

# ========================================
# Outputs
# ========================================

output "vpc_id" {
  description = "ID of the VPC"
  value       = alicloud_vpc.vpc.id
}

output "vpc_name" {
  description = "Name of the VPC"
  value       = alicloud_vpc.vpc.vpc_name
}

output "vpc_cidr" {
  description = "CIDR block of the VPC"
  value       = alicloud_vpc.vpc.cidr_block
}

output "security_group_id" {
  description = "ID of the Security Group"
  value       = alicloud_security_group.sg.id
}

{{vSwitchOutputs}}
