#!/bin/bash
# Google Cloud CLI Script to Create VPC and Subnets
# Generated by ipcalc.cloud

# ========================================
# Variables
# ========================================
PROJECT_ID="your-project-id"
VPC_NAME="myproject-vpc"
ROUTING_MODE="regional"  # or "global"
{{spokeVPCVariables}}

# Set the project
gcloud config set project "${PROJECT_ID}"

# ========================================
# Create Hub VPC (auto mode disabled)
# ========================================
echo "Creating Hub VPC..."
gcloud compute networks create "${VPC_NAME}" \
  --subnet-mode=custom \
  --bgp-routing-mode=${ROUTING_MODE} \
  --mtu=1460

echo "Hub VPC ${VPC_NAME} created successfully"

# ========================================
# Create Hub Subnets
# ========================================
{{subnetCreation}}

# ========================================
# Create Spoke VPCs and Subnets
# ========================================
{{spokeVPCCreation}}

# ========================================
# Create VPC Peerings
# ========================================
{{spokePeeringCreation}}

echo "GCP VPC and Subnets created successfully!"

# ========================================
# Display VPC and Subnets
# ========================================
echo "Hub VPC Details:"
gcloud compute networks describe "${VPC_NAME}"

echo "Hub Subnet Details:"
gcloud compute networks subnets list --network="${VPC_NAME}"

echo "VPC Peerings:"
gcloud compute networks peerings list --network="${VPC_NAME}"
