#!/bin/bash
# Azure CLI Script to Create VNet and Subnets
# Generated by ipcalc.cloud

# ========================================
# Variables
# ========================================
PREFIX="myproject"
LOCATION="eastus"
RESOURCE_GROUP="${PREFIX}-rg"
VNET_NAME="${PREFIX}-vnet"
VNET_CIDR="{{vnetCidr}}"

{{subnetVariables}}
{{spokeVnetVariables}}

# ========================================
# Create Resource Group
# ========================================
echo "Creating Resource Group: ${RESOURCE_GROUP}"
az group create \
  --name "${RESOURCE_GROUP}" \
  --location "${LOCATION}"

# ========================================
# Create Virtual Network (Hub)
# ========================================
echo "Creating Virtual Network: ${VNET_NAME}"
az network vnet create \
  --resource-group "${RESOURCE_GROUP}" \
  --name "${VNET_NAME}" \
  --address-prefix "${VNET_CIDR}" \
  --location "${LOCATION}"

# ========================================
# Create Subnets
# ========================================
{{subnetCreation}}

{{spokeVnetCreation}}
{{vnetPeering}}

echo "Azure VNet and Subnets created successfully!"
