# PowerShell Script to Create Azure VNet and Subnets
# Generated by ipcalc.cloud
# Requires: Az PowerShell Module

#Requires -Modules Az.Network, Az.Resources

# ========================================
# Variables
# ========================================

$Prefix = "myproject"
$Location = "eastus"
$ResourceGroupName = "${Prefix}-rg"
$VNetName = "${Prefix}-vnet"
$VNetCidr = "{{vnetCidr}}"

{{subnetVariables}}
{{spokeVnetVariables}}

$Tags = @{
    Environment = "Production"
    ManagedBy = "PowerShell"
}

# ========================================
# Create Resource Group
# ========================================

Write-Host "Creating Resource Group: $ResourceGroupName" -ForegroundColor Cyan
try {
    $rg = New-AzResourceGroup `
        -Name $ResourceGroupName `
        -Location $Location `
        -Tag $Tags `
        -Force
    Write-Host "✓ Resource Group created successfully" -ForegroundColor Green
}
catch {
    Write-Error "Failed to create Resource Group: $_"
    exit 1
}

# ========================================
# Create Subnet Configurations
# ========================================

Write-Host "Creating subnet configurations..." -ForegroundColor Cyan
{{subnetConfigurations}}

# ========================================
# Create Virtual Network (Hub)
# ========================================

Write-Host "Creating Virtual Network: $VNetName" -ForegroundColor Cyan
try {
    $vnet = New-AzVirtualNetwork `
        -Name $VNetName `
        -ResourceGroupName $ResourceGroupName `
        -Location $Location `
        -AddressPrefix $VNetCidr `
        -Subnet {{subnetConfigList}} `
        -Tag $Tags
    Write-Host "✓ Virtual Network created successfully" -ForegroundColor Green
}
catch {
    Write-Error "Failed to create Virtual Network: $_"
    exit 1
}

{{spokeVnetCreation}}
{{vnetPeering}}

# ========================================
# Display Results
# ========================================

Write-Host "`n========================================" -ForegroundColor Yellow
Write-Host "Deployment Summary" -ForegroundColor Yellow
Write-Host "========================================" -ForegroundColor Yellow
Write-Host "Resource Group:    $($rg.ResourceGroupName)" -ForegroundColor White
Write-Host "Location:          $($rg.Location)" -ForegroundColor White
Write-Host "VNet Name:         $($vnet.Name)" -ForegroundColor White
Write-Host "VNet ID:           $($vnet.Id)" -ForegroundColor White
Write-Host "Address Space:     $($vnet.AddressSpace.AddressPrefixes -join ', ')" -ForegroundColor White
Write-Host "`nSubnets:" -ForegroundColor White
foreach ($subnet in $vnet.Subnets) {
    Write-Host "  - $($subnet.Name): $($subnet.AddressPrefix)" -ForegroundColor Gray
}
Write-Host "========================================`n" -ForegroundColor Yellow

# ========================================
# Output Objects (for use in scripts)
# ========================================

return @{
    ResourceGroup = $rg
    VirtualNetwork = $vnet
    Subnets = $vnet.Subnets
}
