# Terraform Configuration for Azure VNet and Subnets
# Generated by ipcalc-for-cloud

# ========================================
# Provider Configuration
# ========================================

terraform {
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "~> 3.0"
    }
  }
}

provider "azurerm" {
  features {}
}

# ========================================
# Variables
# ========================================

variable "prefix" {
  description = "Prefix for resource naming"
  type        = string
  default     = "myproject"
}

variable "location" {
  description = "Azure region for resources"
  type        = string
  default     = "eastus"
}

variable "vnet_cidr" {
  description = "CIDR block for the Virtual Network"
  type        = string
  default     = "{{vnetCidr}}"
}

{{subnetVariables}}

# ========================================
# Resource Group
# ========================================

resource "azurerm_resource_group" "rg" {
  name     = "${var.prefix}-rg"
  location = var.location

  tags = {
    Environment = "Production"
    ManagedBy   = "Terraform"
  }
}

# ========================================
# Virtual Network
# ========================================

resource "azurerm_virtual_network" "vnet" {
  name                = "${var.prefix}-vnet"
  address_space       = [var.vnet_cidr]
  location            = azurerm_resource_group.rg.location
  resource_group_name = azurerm_resource_group.rg.name

  tags = {
    Environment = "Production"
    ManagedBy   = "Terraform"
  }
}

# ========================================
# Subnets
# ========================================

{{subnetResources}}

{{spokeVnetResources}}
{{vnetPeeringResources}}

# ========================================
# Outputs
# ========================================

output "resource_group_name" {
  description = "Name of the resource group"
  value       = azurerm_resource_group.rg.name
}

output "vnet_name" {
  description = "Name of the virtual network"
  value       = azurerm_virtual_network.vnet.name
}

output "vnet_id" {
  description = "ID of the virtual network"
  value       = azurerm_virtual_network.vnet.id
}

{{subnetOutputs}}
{{spokeVnetOutputs}}
