"""
Network diagram code generator

This module generates Python code that uses the diagrams library
to create network architecture diagrams.
"""

from typing import List
from api.core.ip_calculator import SubnetInfo
from api.diagrams.templates import azure


class DiagramGenerator:
    """Generates diagram code for various cloud providers"""

    @staticmethod
    def generate_azure_diagram(
        network_cidr: str,
        subnets: List[SubnetInfo],
        diagram_type: str = "simple"
    ) -> str:
        """
        Generate Python code for Azure network diagram

        Args:
            network_cidr: Network CIDR notation (e.g., "10.0.0.0/16")
            subnets: List of subnet information
            diagram_type: Type of diagram ("simple" or "detailed")

        Returns:
            Python code string that can be executed to generate the diagram
        """
        if diagram_type == "detailed":
            return azure.generate_detailed_azure_diagram(network_cidr, subnets)
        else:
            return azure.generate_simple_azure_diagram(network_cidr, subnets)

    @staticmethod
    def generate_aws_diagram(
        network_cidr: str,
        subnets: List[SubnetInfo],
        diagram_type: str = "simple"
    ) -> str:
        """
        Generate Python code for AWS VPC diagram

        Args:
            network_cidr: Network CIDR notation (e.g., "10.0.0.0/16")
            subnets: List of subnet information
            diagram_type: Type of diagram ("simple" or "detailed")

        Returns:
            Python code string that can be executed to generate the diagram
        """
        # Placeholder for AWS diagram generation
        network_name = network_cidr.replace('/', '_').replace('.', '_')

        code = f'''#!/usr/bin/env python3
"""
AWS VPC Diagram
Generated by ipcalc API

Network: {network_cidr}
Subnets: {len(subnets)}
"""

from diagrams import Diagram, Cluster
from diagrams.aws.network import VPC, PublicSubnet, PrivateSubnet

with Diagram("AWS VPC - {network_cidr}",
             filename="aws_vpc_{network_name}",
             show=False):

    with Cluster("VPC {network_cidr}"):
        vpc_subnets = []

'''

        for i, subnet in enumerate(subnets):
            code += f'        subnet{i+1} = PublicSubnet("{subnet.cidr}\\n{subnet.usable_ips} usable IPs")\n'
            code += f'        vpc_subnets.append(subnet{i+1})\n'

        code += '''
print("AWS VPC diagram generated successfully!")
print("Output file: aws_vpc_{network_name}.png")
'''

        return code

    @staticmethod
    def generate_gcp_diagram(
        network_cidr: str,
        subnets: List[SubnetInfo],
        diagram_type: str = "simple"
    ) -> str:
        """
        Generate Python code for GCP VPC diagram

        Args:
            network_cidr: Network CIDR notation (e.g., "10.0.0.0/16")
            subnets: List of subnet information
            diagram_type: Type of diagram ("simple" or "detailed")

        Returns:
            Python code string that can be executed to generate the diagram
        """
        # Placeholder for GCP diagram generation
        network_name = network_cidr.replace('/', '_').replace('.', '_')

        code = f'''#!/usr/bin/env python3
"""
GCP VPC Diagram
Generated by ipcalc API

Network: {network_cidr}
Subnets: {len(subnets)}
"""

from diagrams import Diagram, Cluster
from diagrams.gcp.network import VPC

with Diagram("GCP VPC - {network_cidr}",
             filename="gcp_vpc_{network_name}",
             show=False):

    vpc = VPC("VPC Network\\n{network_cidr}")

print("GCP VPC diagram generated successfully!")
print("Output file: gcp_vpc_{network_name}.png")
'''

        return code

    @staticmethod
    def generate_diagram(
        provider: str,
        network_cidr: str,
        subnets: List[SubnetInfo],
        diagram_type: str = "simple"
    ) -> str:
        """
        Generate diagram code for any supported provider

        Args:
            provider: Cloud provider name
            network_cidr: Network CIDR notation
            subnets: List of subnet information
            diagram_type: Type of diagram ("simple" or "detailed")

        Returns:
            Python code string that can be executed to generate the diagram

        Raises:
            ValueError: If provider is not supported
        """
        generators = {
            "azure": DiagramGenerator.generate_azure_diagram,
            "aws": DiagramGenerator.generate_aws_diagram,
            "gcp": DiagramGenerator.generate_gcp_diagram,
        }

        if provider not in generators:
            # For unsupported providers, generate a generic diagram
            network_name = network_cidr.replace('/', '_').replace('.', '_')
            return f'''#!/usr/bin/env python3
"""
Generic Network Diagram
Generated by ipcalc API

Provider: {provider}
Network: {network_cidr}
Subnets: {len(subnets)}
"""

from diagrams import Diagram

with Diagram("{provider.upper()} Network - {network_cidr}",
             filename="{provider}_network_{network_name}",
             show=False):
    pass

print("Note: Detailed diagram generation for {provider} is not yet implemented.")
print("Output file: {provider}_network_{network_name}.png")
'''

        return generators[provider](network_cidr, subnets, diagram_type)

    @staticmethod
    def get_execution_instructions(provider: str, diagram_type: str) -> str:
        """
        Get instructions for executing the generated diagram code

        Args:
            provider: Cloud provider name
            diagram_type: Type of diagram

        Returns:
            Instructions string
        """
        return f"""To generate the diagram:
1. Save the Python code to a file (e.g., 'network_diagram.py')
2. Install dependencies: pip install diagrams
3. Install Graphviz:
   - Ubuntu/Debian: sudo apt-get install graphviz
   - macOS: brew install graphviz
   - Windows: Download from https://graphviz.org/download/
4. Run the script: python network_diagram.py
5. The diagram will be saved as a PNG file in the current directory

The generated diagram shows:
- {provider.upper()} network topology
- All subnets with their CIDR blocks
- Usable IP counts per subnet
- {"Availability zones and security groups (detailed view)" if diagram_type == "detailed" else "Basic network structure"}
"""

    @staticmethod
    def get_diagram_description(provider: str, network_cidr: str, subnet_count: int, diagram_type: str) -> str:
        """
        Get a description of the generated diagram

        Args:
            provider: Cloud provider name
            network_cidr: Network CIDR
            subnet_count: Number of subnets
            diagram_type: Type of diagram

        Returns:
            Description string
        """
        provider_names = {
            "azure": "Azure Virtual Network",
            "aws": "AWS VPC",
            "gcp": "GCP VPC",
            "oracle": "Oracle VCN",
            "alicloud": "Alibaba Cloud VPC",
            "onpremises": "On-Premises Network"
        }

        provider_name = provider_names.get(provider, f"{provider.upper()} Network")
        detail = "with detailed security groups and routing" if diagram_type == "detailed" else ""

        return f"{provider_name} ({network_cidr}) with {subnet_count} subnet(s) {detail}".strip()
