#!/bin/bash
# Oracle Cloud Infrastructure CLI Script to Create VCN and Subnets
# Generated by ipcalc.cloud

# ========================================
# Variables
# ========================================
COMPARTMENT_ID="ocid1.compartment.oc1..your-compartment-id"
VCN_NAME="myproject-vcn"
VCN_CIDR="{{vcnCidr}}"
VCN_DNS_LABEL="myprojectvcn"

# ========================================
# Create VCN
# ========================================
echo "Creating VCN..."
VCN_ID=$(oci network vcn create \
  --compartment-id "${COMPARTMENT_ID}" \
  --cidr-block "${VCN_CIDR}" \
  --display-name "${VCN_NAME}" \
  --dns-label "${VCN_DNS_LABEL}" \
  --query 'data.id' \
  --raw-output)

echo "VCN created with ID: ${VCN_ID}"

# ========================================
# Create Internet Gateway
# ========================================
echo "Creating Internet Gateway..."
IGW_ID=$(oci network internet-gateway create \
  --compartment-id "${COMPARTMENT_ID}" \
  --vcn-id "${VCN_ID}" \
  --is-enabled true \
  --display-name "${VCN_NAME}-igw" \
  --query 'data.id' \
  --raw-output)

echo "Internet Gateway created with ID: ${IGW_ID}"

# ========================================
# Create Route Table
# ========================================
echo "Creating Route Table..."
RT_ID=$(oci network route-table create \
  --compartment-id "${COMPARTMENT_ID}" \
  --vcn-id "${VCN_ID}" \
  --display-name "${VCN_NAME}-rt" \
  --route-rules '[{"destination": "0.0.0.0/0", "destinationType": "CIDR_BLOCK", "networkEntityId": "'${IGW_ID}'"}]' \
  --query 'data.id' \
  --raw-output)

echo "Route Table created with ID: ${RT_ID}"

# ========================================
# Create Security List
# ========================================
echo "Creating Security List..."
SL_ID=$(oci network security-list create \
  --compartment-id "${COMPARTMENT_ID}" \
  --vcn-id "${VCN_ID}" \
  --display-name "${VCN_NAME}-sl" \
  --egress-security-rules '[{"destination": "0.0.0.0/0", "protocol": "all", "isStateless": false}]' \
  --ingress-security-rules '[{"source": "{{vcnCidr}}", "protocol": "all", "isStateless": false}]' \
  --query 'data.id' \
  --raw-output)

echo "Security List created with ID: ${SL_ID}"

# ========================================
# Create Subnets
# ========================================
{{subnetCreation}}

echo "OCI VCN and Subnets created successfully!"

# ========================================
# Display VCN and Subnets
# ========================================
echo "VCN Details:"
oci network vcn get --vcn-id "${VCN_ID}"

echo "Subnet Details:"
oci network subnet list --compartment-id "${COMPARTMENT_ID}" --vcn-id "${VCN_ID}"
