"""
Azure network diagram templates
"""

from typing import List
from api.core.ip_calculator import SubnetInfo


def generate_simple_azure_diagram(network_cidr: str, subnets: List[SubnetInfo]) -> str:
    """
    Generate Python code for a simple Azure network diagram

    Args:
        network_cidr: The network CIDR (e.g., "10.0.0.0/16")
        subnets: List of subnet information

    Returns:
        Python code string that can be executed to generate the diagram
    """
    subnet_count = len(subnets)
    network_name = network_cidr.replace('/', '_').replace('.', '_')

    # Build subnet definitions
    subnet_defs = []
    subnet_vars = []
    for i, subnet in enumerate(subnets):
        var_name = f"subnet{i + 1}"
        subnet_vars.append(var_name)
        label = f"{subnet.cidr}\\n{subnet.usable_ips} usable IPs"
        if subnet.availability_zone:
            label += f"\\nZone: {subnet.availability_zone}"
        subnet_defs.append(f'    {var_name} = Subnets("{label}")')

    subnet_defs_code = '\n'.join(subnet_defs)

    # Generate the Python code
    code = f'''#!/usr/bin/env python3
"""
Azure Virtual Network Diagram
Generated by ipcalc API

Network: {network_cidr}
Subnets: {subnet_count}
"""

from diagrams import Diagram, Cluster, Edge
from diagrams.azure.network import VirtualNetworks, Subnets, NetworkSecurityGroups

# Configure diagram
graph_attr = {{
    "fontsize": "16",
    "bgcolor": "white",
    "pad": "0.5"
}}

with Diagram("Azure Virtual Network - {network_cidr}",
             filename="azure_network_{network_name}",
             show=False,
             direction="TB",
             graph_attr=graph_attr):

    vnet = VirtualNetworks("VNet\\n{network_cidr}")
    nsg = NetworkSecurityGroups("Network\\nSecurity Group")

    # Define subnets
{subnet_defs_code}

    # Connect VNet to NSG
    vnet >> Edge(color="darkblue", style="dashed") >> nsg

    # Connect subnets to VNet
    subnets_list = [{', '.join(subnet_vars)}]
    vnet >> Edge(color="blue") >> subnets_list

print("Diagram generated successfully!")
print("Output file: azure_network_{network_name}.png")
'''

    return code


def generate_detailed_azure_diagram(network_cidr: str, subnets: List[SubnetInfo]) -> str:
    """
    Generate Python code for a detailed Azure network diagram with zones

    Args:
        network_cidr: The network CIDR (e.g., "10.0.0.0/16")
        subnets: List of subnet information

    Returns:
        Python code string that can be executed to generate the diagram
    """
    subnet_count = len(subnets)
    network_name = network_cidr.replace('/', '_').replace('.', '_')

    # Group subnets by availability zone
    zones = {}
    for subnet in subnets:
        zone = subnet.availability_zone or "default"
        if zone not in zones:
            zones[zone] = []
        zones[zone].append(subnet)

    # Build zone clusters with subnets
    zone_code = []
    all_subnet_vars = []

    if len(zones) > 1 and list(zones.keys())[0] != "default":
        # Multi-zone layout
        for zone_name, zone_subnets in zones.items():
            zone_code.append(f'    with Cluster("{zone_name}"):')
            for i, subnet in enumerate(zone_subnets):
                var_name = f"subnet_{zone_name.replace('-', '_')}_{i + 1}"
                all_subnet_vars.append(var_name)
                label = f"{subnet.cidr}\\n{subnet.usable_ips} usable IPs"
                zone_code.append(f'        {var_name} = Subnets("{label}")')
            zone_code.append("")
    else:
        # Single zone or no zones - simple layout
        for i, subnet in enumerate(subnets):
            var_name = f"subnet{i + 1}"
            all_subnet_vars.append(var_name)
            label = f"{subnet.cidr}\\n{subnet.usable_ips} usable IPs"
            zone_code.append(f'    {var_name} = Subnets("{label}")')

    zone_code_str = '\n'.join(zone_code)

    # Generate the Python code
    code = f'''#!/usr/bin/env python3
"""
Azure Virtual Network Diagram (Detailed)
Generated by ipcalc API

Network: {network_cidr}
Subnets: {subnet_count}
"""

from diagrams import Diagram, Cluster, Edge
from diagrams.azure.network import VirtualNetworks, Subnets, NetworkSecurityGroups, RouteTables, ApplicationGateway
from diagrams.azure.compute import VM

# Configure diagram
graph_attr = {{
    "fontsize": "16",
    "bgcolor": "white",
    "pad": "0.5"
}}

with Diagram("Azure Virtual Network (Detailed) - {network_cidr}",
             filename="azure_network_detailed_{network_name}",
             show=False,
             direction="LR",
             graph_attr=graph_attr):

    vnet = VirtualNetworks("Virtual Network\\n{network_cidr}")
    nsg = NetworkSecurityGroups("NSG")
    route_table = RouteTables("Route Table")

    # Define subnets organized by zones
{zone_code_str}

    # Network infrastructure
    vnet >> Edge(color="darkblue", style="bold") >> [nsg, route_table]

    # Connect all subnets to VNet
    subnets_list = [{', '.join(all_subnet_vars)}]
    vnet >> Edge(color="blue") >> subnets_list

    # Apply NSG to subnets
    subnets_list >> Edge(color="red", style="dashed", label="security") >> nsg

print("Detailed diagram generated successfully!")
print("Output file: azure_network_detailed_{network_name}.png")
'''

    return code
