#!/usr/bin/env python3
"""
Azure D2 Diagram Generator

Generates D2 diagram source code from ipcalc network data (VNets, subnets,
resource groups, hub-spoke peering). Output can be rendered to SVG/PNG with
the D2 CLI: d2 --layout=elk diagram.d2 diagram.svg

Uses the py-d2 library for shape and connection construction. D2 class
assignments and icon properties are not supported by py-d2 natively, so
_AzureShape and _AzureConnection extend the base classes to add them.
The header and classes block are emitted as raw D2 text since py-d2 has
no support for top-level directives.
"""

import subprocess
from typing import Any

from py_d2 import D2Connection, D2Diagram, D2Shape
from py_d2.connection import Direction


class _AzureShape(D2Shape):
    """D2Shape with D2 class and icon support."""

    def __init__(
        self,
        *args: Any,
        d2_class: str | None = None,
        icon: str | None = None,
        **kwargs: Any,
    ) -> None:
        super().__init__(*args, **kwargs)
        self._d2_class = d2_class
        self._icon = icon

    def lines(self) -> list[str]:
        base = super().lines()
        extras = []
        if self._d2_class:
            extras.append(f"class: {self._d2_class}")
        if self._icon:
            extras.append(f"icon: {self._icon}")
        if not extras:
            return base
        if base[-1] == "}":
            return base[:-1] + [f"  {e}" for e in extras] + ["}"]
        # Leaf node with no block yet — open one.
        return [base[0] + " {"] + [f"  {e}" for e in extras] + ["}"]


class _AzureConnection(D2Connection):
    """D2Connection with D2 class support."""

    def __init__(self, *args: Any, d2_class: str | None = None, **kwargs: Any) -> None:
        super().__init__(*args, **kwargs)
        self._d2_class = d2_class

    def lines(self) -> list[str]:
        base = super().lines()
        if self._d2_class:
            return [base[0] + " {", f"  class: {self._d2_class}", "}"]
        return base


class AzureDiagramGenerator:
    """Generates D2 diagram code for Azure networking from ipcalc data."""

    DEFAULT_ICON_BASE_URL = "https://www.ipcalc.cloud/api/icons"

    def __init__(self, icon_base_url: str | None = None) -> None:
        self.ICON_BASE_URL = icon_base_url or self.DEFAULT_ICON_BASE_URL

    _ICON_PATHS: dict[str, str] = {
        "vnet":    "networking/10061-icon-service-Virtual-Networks.svg",
        "peering": "other/01285-icon-service-Peerings.svg",
    }

    def generate(self, data: dict[str, Any]) -> str:
        """Generate D2 diagram source from ipcalc network data.

        Args:
            data: Dict with keys: vnetCidr, subnets, peeringEnabled,
                  namePrefix (optional, default "ipcalc"),
                  optionally spokeVNets (list of spoke dicts with cidr/subnets).

        Returns:
            D2 source code as a string.
        """
        prefix = data.get("namePrefix") or "ipcalc"
        if data.get("peeringEnabled") and data.get("spokeVNets"):
            shapes, connections = self._build_hub_spoke(data, prefix)
        else:
            shapes, connections = self._build_simple(data, prefix)

        body = str(D2Diagram(shapes=shapes, connections=connections))
        return self._generate_header() + "\n" + self._generate_classes() + "\n" + body

    # ------------------------------------------------------------------
    # Header / classes  (raw D2 — py-d2 has no top-level directive support)
    # ------------------------------------------------------------------

    def _generate_header(self) -> str:
        return (
            "# Azure Network Diagram — generated by ipcalc\n"
            "# Render: d2 --layout=elk diagram.d2 diagram.svg\n"
            "\n"
            "direction: right\n"
        )

    def _generate_classes(self) -> str:
        return (
            "classes: {\n"
            "  resource_group: {\n"
            "    style.fill: \"#FFF3E0\"\n"
            "    style.stroke: \"#E65100\"\n"
            "    style.stroke-width: 2\n"
            "    style.border-radius: 8\n"
            "  }\n"
            "  vnet: {\n"
            "    style.fill: \"#E3F2FD\"\n"
            "    style.stroke: \"#1565C0\"\n"
            "    style.stroke-width: 2\n"
            "  }\n"
            "  subnet: {\n"
            "    style.fill: \"#F3E5F5\"\n"
            "    style.stroke: \"#6A1B9A\"\n"
            "  }\n"
            "  peering: {\n"
            "    style.stroke: \"#FF6D00\"\n"
            "    style.stroke-width: 2\n"
            "    style.stroke-dash: 5\n"
            "  }\n"
            "}\n"
        )

    # ------------------------------------------------------------------
    # Shape builders
    # ------------------------------------------------------------------

    def _build_simple(
        self, data: dict[str, Any], prefix: str
    ) -> tuple[list[_AzureShape], list[_AzureConnection]]:
        rg_id = self._sanitize_id(f"{prefix}_rg")
        vnet_id = self._sanitize_id(f"{prefix}_vnet")
        vnet = self._build_vnet_shape(
            vnet_id,
            f'"VNet: {prefix}-vnet\\n{data["vnetCidr"]}"',
            data["subnets"],
        )
        rg = _AzureShape(
            name=rg_id,
            label=f'"Resource Group: {prefix}-rg"',
            shapes=[vnet],
            d2_class="resource_group",
        )
        return [rg], []

    def _build_hub_spoke(
        self, data: dict[str, Any], prefix: str
    ) -> tuple[list[_AzureShape], list[_AzureConnection]]:
        shapes: list[_AzureShape] = []
        connections: list[_AzureConnection] = []

        hub_rg_id = "hub_rg"
        hub_vnet_id = "hub_vnet"
        hub_vnet = self._build_vnet_shape(
            hub_vnet_id,
            f'"Hub VNet\\n{data["vnetCidr"]}"',
            data["subnets"],
        )
        shapes.append(_AzureShape(
            name=hub_rg_id,
            label='"Resource Group: hub-rg"',
            shapes=[hub_vnet],
            d2_class="resource_group",
        ))

        for spoke in data.get("spokeVNets", []):
            idx = spoke["index"]
            spoke_rg_id = f"spoke{idx}_rg"
            spoke_vnet_id = f"spoke{idx}_vnet"
            spoke_vnet = self._build_vnet_shape(
                spoke_vnet_id,
                f'"Spoke {idx} VNet\\n{spoke["cidr"]}"',
                spoke["subnets"],
            )
            shapes.append(_AzureShape(
                name=spoke_rg_id,
                label=f'"Resource Group: spoke{idx}-rg"',
                shapes=[spoke_vnet],
                d2_class="resource_group",
            ))
            connections.append(_AzureConnection(
                f"{hub_rg_id}.{hub_vnet_id}",
                f"{spoke_rg_id}.{spoke_vnet_id}",
                label="VNet Peering",
                direction=Direction.BOTH,
                d2_class="peering",
            ))

        return shapes, connections

    def _build_vnet_shape(
        self, vnet_id: str, label: str, subnets: list[dict[str, Any]]
    ) -> _AzureShape:
        vnet_icon = f"{self.ICON_BASE_URL}/{self._ICON_PATHS['vnet']}"
        subnet_shapes = [
            _AzureShape(
                name=self._sanitize_id(s["name"]),
                label=f'"{self._subnet_label(s)}"',
                d2_class="subnet",
            )
            for s in subnets
        ]
        return _AzureShape(
            name=vnet_id,
            label=label,
            shapes=subnet_shapes,
            d2_class="vnet",
            icon=vnet_icon,
        )

    # ------------------------------------------------------------------
    # SVG rendering  (py-d2 generates D2 text only; d2 CLI renders SVG)
    # ------------------------------------------------------------------

    def render_svg(self, d2_source: str, layout: str = "elk") -> str:
        """Render D2 source to SVG using the d2 CLI.

        Args:
            d2_source: D2 diagram source code.
            layout:    D2 layout engine (default: elk).

        Returns:
            SVG content as a string.

        Raises:
            FileNotFoundError: if the d2 binary is not on PATH.
            subprocess.CalledProcessError: if d2 exits with a non-zero status.
        """
        result = subprocess.run(
            ["d2", f"--layout={layout}", "-", "-"],
            input=d2_source,
            capture_output=True,
            text=True,
            check=True,
        )
        return result.stdout

    # ------------------------------------------------------------------
    # Helpers
    # ------------------------------------------------------------------

    def _sanitize_id(self, name: str) -> str:
        """Replace characters that are invalid or ambiguous in D2 IDs."""
        result = ""
        for ch in name:
            if ch in (" ", "-", ".", "/"):
                result += "_"
            else:
                result += ch
        return result

    def _subnet_label(self, subnet: dict[str, Any]) -> str:
        return f"{subnet['name']}\\n{subnet['cidr']}"
