#!/usr/bin/env python3
"""
Azure D2 Diagram Generator

Generates D2 diagram source code from ipcalc network data (VNets, subnets,
resource groups, hub-spoke peering). Output can be rendered to SVG/PNG with
the D2 CLI: d2 --layout=elk diagram.d2 diagram.svg
"""

from typing import Any


class AzureDiagramGenerator:
    """Generates D2 diagram code for Azure networking from ipcalc data."""

    ICON_BASE_URL = (
        "https://raw.githubusercontent.com/miiitch/skill-diagram-generators"
        "/refs/heads/main/png/Icons"
    )

    # Icon paths relative to ICON_BASE_URL for the resource types ipcalc produces
    _ICON_PATHS: dict[str, str] = {
        "vnet":    "networking/10061-icon-service-Virtual-Networks.png",
        "subnet":  "networking/10063-icon-service-Virtual-Networks-Subnets.png",
        "peering": "networking/10064-icon-service-Virtual-Network-Peerings.png",
    }

    def generate(self, data: dict[str, Any]) -> str:
        """Generate D2 diagram source from ipcalc network data.

        Args:
            data: Dict with keys: vnetCidr, subnets, peeringEnabled,
                  optionally spokeVNets (list of spoke dicts with cidr/subnets).

        Returns:
            D2 source code as a string.
        """
        prefix = "myproject"
        if data.get("peeringEnabled") and data.get("spokeVNets"):
            body = self._generate_hub_spoke(data, prefix)
        else:
            body = self._generate_simple(data, prefix)

        return (
            self._generate_header()
            + "\n"
            + self._generate_classes()
            + "\n"
            + body
        )

    # ------------------------------------------------------------------
    # Header / classes
    # ------------------------------------------------------------------

    def _generate_header(self) -> str:
        return (
            "# Azure Network Diagram — generated by ipcalc\n"
            "# Render: d2 --layout=elk diagram.d2 diagram.svg\n"
            "\n"
            "direction: right\n"
        )

    def _generate_classes(self) -> str:
        return (
            "classes: {\n"
            "  resource_group: {\n"
            "    style.fill: \"#FFF3E0\"\n"
            "    style.stroke: \"#E65100\"\n"
            "    style.stroke-width: 2\n"
            "    style.border-radius: 8\n"
            "  }\n"
            "  vnet: {\n"
            "    style.fill: \"#E3F2FD\"\n"
            "    style.stroke: \"#1565C0\"\n"
            "    style.stroke-width: 2\n"
            "  }\n"
            "  subnet: {\n"
            "    style.fill: \"#F3E5F5\"\n"
            "    style.stroke: \"#6A1B9A\"\n"
            "  }\n"
            "  peering: {\n"
            "    style.stroke: \"#FF6D00\"\n"
            "    style.stroke-width: 2\n"
            "    style.stroke-dash: 5\n"
            "  }\n"
            "}\n"
        )

    # ------------------------------------------------------------------
    # Single VNet
    # ------------------------------------------------------------------

    def _generate_simple(self, data: dict[str, Any], prefix: str) -> str:
        rg_id = self._sanitize_id(f"{prefix}_rg")
        rg_label = f"Resource Group: {prefix}-rg"
        vnet_id = self._sanitize_id(f"{prefix}_vnet")
        vnet_label = f"VNet: {prefix}-vnet\\n{data['vnetCidr']}"

        vnet_block = self._generate_vnet_block(
            vnet_id, vnet_label, data["vnetCidr"], data["subnets"]
        )
        return self._generate_rg_block(rg_id, rg_label, vnet_block)

    # ------------------------------------------------------------------
    # Hub-spoke topology
    # ------------------------------------------------------------------

    def _generate_hub_spoke(self, data: dict[str, Any], prefix: str) -> str:
        lines: list[str] = []

        # Hub RG + VNet
        hub_rg_id = "hub_rg"
        hub_vnet_id = "hub_vnet"
        hub_vnet_label = f"Hub VNet\\n{data['vnetCidr']}"
        hub_vnet_block = self._generate_vnet_block(
            hub_vnet_id, hub_vnet_label, data["vnetCidr"], data["subnets"]
        )
        lines.append(
            self._generate_rg_block(hub_rg_id, "Resource Group: hub-rg", hub_vnet_block)
        )

        # Spoke RGs + VNets
        spoke_ids: list[tuple[str, str]] = []  # (rg_id, vnet_id)
        for spoke in data.get("spokeVNets", []):
            idx = spoke["index"]
            spoke_rg_id = f"spoke{idx}_rg"
            spoke_vnet_id = f"spoke{idx}_vnet"
            spoke_vnet_label = f"Spoke {idx} VNet\\n{spoke['cidr']}"
            spoke_vnet_block = self._generate_vnet_block(
                spoke_vnet_id, spoke_vnet_label, spoke["cidr"], spoke["subnets"]
            )
            rg_label = f"Resource Group: spoke{idx}-rg"
            lines.append(
                self._generate_rg_block(spoke_rg_id, rg_label, spoke_vnet_block)
            )
            spoke_ids.append((spoke_rg_id, spoke_vnet_id))

        # Peering edges (bidirectional hub <-> each spoke)
        if spoke_ids:
            lines.append("# VNet peering connections (bidirectional)\n")
            for spoke_rg_id, spoke_vnet_id in spoke_ids:
                lines.append(
                    f"{hub_rg_id}.{hub_vnet_id} <-> "
                    f"{spoke_rg_id}.{spoke_vnet_id}: "
                    f"\"VNet Peering\" {{\n  class: peering\n}}\n"
                )

        return "\n".join(lines)

    # ------------------------------------------------------------------
    # Building blocks
    # ------------------------------------------------------------------

    def _generate_vnet_block(
        self,
        vnet_id: str,
        label: str,
        cidr: str,
        subnets: list[dict[str, Any]],
    ) -> str:
        # D2 does not allow shape:image on a node that has children, so the
        # VNet is a plain styled container. Subnets are leaf nodes with icons.
        icon_url = f"{self.ICON_BASE_URL}/{self._ICON_PATHS['subnet']}"
        lines = [
            f"{vnet_id}: \"{label}\" {{",
            "  class: vnet",
        ]
        for subnet in subnets:
            subnet_id = self._sanitize_id(subnet["name"])
            subnet_label = self._subnet_label(subnet)
            lines.append(
                f"  {subnet_id}: \"{subnet_label}\" {{\n"
                f"    class: subnet\n"
                f"    shape: image\n"
                f"    icon: {icon_url}\n"
                f"  }}"
            )
        lines.append("}")
        return "\n".join(lines) + "\n"

    def _generate_rg_block(self, rg_id: str, label: str, vnet_block: str) -> str:
        indented_vnet = "\n".join(
            "  " + line if line else ""
            for line in vnet_block.splitlines()
        )
        return (
            f"{rg_id}: \"{label}\" {{\n"
            "  class: resource_group\n"
            f"{indented_vnet}\n"
            "}\n"
        )

    # ------------------------------------------------------------------
    # Helpers
    # ------------------------------------------------------------------

    def _sanitize_id(self, name: str) -> str:
        """Replace characters that are invalid or ambiguous in D2 IDs."""
        result = ""
        for ch in name:
            if ch in (" ", "-", ".", "/"):
                result += "_"
            else:
                result += ch
        return result

    def _subnet_label(self, subnet: dict[str, Any]) -> str:
        """Multi-line D2 label: name + CIDR + usable IP count."""
        usable = subnet.get("usable_ips") or subnet.get("usableIPs", "")
        if usable:
            usable_str = f"{usable:,}" if isinstance(usable, int) else str(usable)
            return f"{subnet['name']}\\n{subnet['cidr']}\\n{usable_str} usable IPs"
        return f"{subnet['name']}\\n{subnet['cidr']}"
