#!/bin/bash
# AWS CLI Script to Create VPC and Subnets
# Generated by ipcalc.cloud

# ========================================
# Variables
# ========================================
PREFIX="myproject"
REGION="us-east-1"
VPC_CIDR="{{vpcCidr}}"

{{subnetVariables}}

# ========================================
# Get Available Availability Zones
# ========================================
echo "Retrieving available Availability Zones for region ${REGION}..."
mapfile -t AVAILABILITY_ZONES < <(aws ec2 describe-availability-zones \
  --region "${REGION}" \
  --filters "Name=state,Values=available" \
  --query 'AvailabilityZones[*].ZoneName' \
  --output text | tr '\t' '\n')

AZ_COUNT=${#AVAILABILITY_ZONES[@]}
echo "Found ${AZ_COUNT} availability zones: ${AVAILABILITY_ZONES[*]}"

# ========================================
# Create VPC
# ========================================
echo "Creating VPC..."
VPC_ID=$(aws ec2 create-vpc \
  --cidr-block "${VPC_CIDR}" \
  --region "${REGION}" \
  --tag-specifications "ResourceType=vpc,Tags=[{Key=Name,Value=${PREFIX}-vpc}]" \
  --query 'Vpc.VpcId' \
  --output text)

echo "VPC ID: ${VPC_ID}"

# ========================================
# Create Subnets
# ========================================
{{subnetCreation}}

echo "AWS VPC and Subnets created successfully!"
