#!/bin/bash
# Alibaba Cloud CLI Script to Create VPC and vSwitches
# Generated by ipcalc.cloud

# ========================================
# Variables
# ========================================
REGION="cn-hangzhou"
VPC_NAME="myproject-vpc"
VPC_CIDR="{{vpcCidr}}"

# ========================================
# Create VPC
# ========================================
echo "Creating VPC..."
VPC_ID=$(aliyun vpc CreateVpc \
  --RegionId "${REGION}" \
  --CidrBlock "${VPC_CIDR}" \
  --VpcName "${VPC_NAME}" \
  --Description "VPC created by IP Calculator" \
  --output cols=VpcId rows=VpcId \
  | tail -n 1 | tr -d ' ')

echo "VPC created with ID: ${VPC_ID}"
echo "Waiting for VPC to be available..."
sleep 5

# ========================================
# Create vSwitches
# ========================================
{{vSwitchCreation}}
echo "Alibaba Cloud VPC and vSwitches created successfully!"

# ========================================
# Display VPC and vSwitches
# ========================================
echo "VPC Details:"
aliyun vpc DescribeVpcAttribute --VpcId "${VPC_ID}"

echo "vSwitch Details:"
aliyun vpc DescribeVSwitches --VpcId "${VPC_ID}"
