#!/bin/bash
# Google Cloud CLI Script to Create VPC and Subnets
# Generated by ipcalc.cloud

# ========================================
# Variables
# ========================================
PROJECT_ID="your-project-id"
VPC_NAME="myproject-vpc"
ROUTING_MODE="regional"  # or "global"

# Set the project
gcloud config set project "${PROJECT_ID}"

# ========================================
# Create VPC (auto mode disabled)
# ========================================
echo "Creating VPC..."
gcloud compute networks create "${VPC_NAME}" \
  --subnet-mode=custom \
  --bgp-routing-mode=${ROUTING_MODE} \
  --mtu=1460

echo "VPC ${VPC_NAME} created successfully"

# ========================================
# Create Subnets
# ========================================
{{subnetCreation}}

echo "GCP VPC and Subnets created successfully!"

# ========================================
# Display VPC and Subnets
# ========================================
echo "VPC Details:"
gcloud compute networks describe "${VPC_NAME}"

echo "Subnet Details:"
gcloud compute networks subnets list --network="${VPC_NAME}"
