# Terraform Configuration for GCP VPC and Subnets
# Generated by ipcalc.cloud

# ========================================
# Provider Configuration
# ========================================

terraform {
  required_providers {
    google = {
      source  = "hashicorp/google"
      version = "~> 5.0"
    }
  }
}

provider "google" {
  project = var.project_id
}

# ========================================
# Variables
# ========================================

variable "project_id" {
  description = "GCP Project ID"
  type        = string
}

variable "vpc_name" {
  description = "Name of the VPC"
  type        = string
  default     = "myproject-vpc"
}

variable "routing_mode" {
  description = "VPC routing mode"
  type        = string
  default     = "REGIONAL"
}

{{subnetVariables}}
{{spokeVPCVariables}}

# ========================================
# Hub VPC Network
# ========================================

resource "google_compute_network" "vpc" {
  name                    = var.vpc_name
  auto_create_subnetworks = false
  routing_mode            = var.routing_mode
  mtu                     = 1460
  project                 = var.project_id

  description = "Hub VPC created by Terraform"
}

# ========================================
# Hub Subnets
# ========================================

{{subnetResources}}

# ========================================
# Spoke VPCs and Subnets
# ========================================

{{spokeVPCResources}}

# ========================================
# VPC Peerings
# ========================================

{{spokePeeringResources}}

# ========================================
# Firewall Rules (Example)
# ========================================

# Allow internal communication
resource "google_compute_firewall" "allow_internal" {
  name    = "${var.vpc_name}-allow-internal"
  network = google_compute_network.vpc.name
  project = var.project_id

  allow {
    protocol = "tcp"
    ports    = ["0-65535"]
  }

  allow {
    protocol = "udp"
    ports    = ["0-65535"]
  }

  allow {
    protocol = "icmp"
  }

  source_ranges = ["{{vpcCidr}}"]
}

# ========================================
# Outputs
# ========================================

output "vpc_name" {
  description = "Name of the VPC"
  value       = google_compute_network.vpc.name
}

output "vpc_id" {
  description = "ID of the VPC"
  value       = google_compute_network.vpc.id
}

output "vpc_self_link" {
  description = "Self link of the VPC"
  value       = google_compute_network.vpc.self_link
}

{{subnetOutputs}}
{{spokeOutputs}}
