# Terraform Configuration for Oracle Cloud Infrastructure VCN and Subnets
# Generated by ipcalc.cloud

# ========================================
# Provider Configuration
# ========================================

terraform {
  required_providers {
    oci = {
      source  = "oracle/oci"
      version = "~> 5.0"
    }
  }
}

provider "oci" {
  # Configure authentication via environment variables or config file
  # OCI_TENANCY_OCID, OCI_USER_OCID, OCI_FINGERPRINT, OCI_PRIVATE_KEY_PATH
}

# ========================================
# Variables
# ========================================

variable "compartment_id" {
  description = "OCI Compartment OCID"
  type        = string
}

variable "vcn_name" {
  description = "Name of the VCN"
  type        = string
  default     = "myproject-vcn"
}

variable "vcn_cidr" {
  description = "CIDR block for the VCN"
  type        = string
  default     = "{{vcnCidr}}"
}

variable "vcn_dns_label" {
  description = "DNS label for the VCN"
  type        = string
  default     = "myprojectvcn"
}

{{subnetVariables}}

# ========================================
# VCN
# ========================================

resource "oci_core_vcn" "vcn" {
  compartment_id = var.compartment_id
  cidr_block     = var.vcn_cidr
  display_name   = var.vcn_name
  dns_label      = var.vcn_dns_label

  freeform_tags = {
    "Environment" = "Production"
    "ManagedBy"   = "Terraform"
  }
}

# ========================================
# Internet Gateway
# ========================================

resource "oci_core_internet_gateway" "igw" {
  compartment_id = var.compartment_id
  vcn_id         = oci_core_vcn.vcn.id
  display_name   = "${var.vcn_name}-igw"
  enabled        = true
}

# ========================================
# Route Table
# ========================================

resource "oci_core_route_table" "rt" {
  compartment_id = var.compartment_id
  vcn_id         = oci_core_vcn.vcn.id
  display_name   = "${var.vcn_name}-rt"

  route_rules {
    destination       = "0.0.0.0/0"
    destination_type  = "CIDR_BLOCK"
    network_entity_id = oci_core_internet_gateway.igw.id
  }
}

# ========================================
# Security List
# ========================================

resource "oci_core_security_list" "sl" {
  compartment_id = var.compartment_id
  vcn_id         = oci_core_vcn.vcn.id
  display_name   = "${var.vcn_name}-sl"

  egress_security_rules {
    destination = "0.0.0.0/0"
    protocol    = "all"
    stateless   = false
  }

  ingress_security_rules {
    source      = var.vcn_cidr
    protocol    = "all"
    stateless   = false
  }
}

# ========================================
# Subnets
# ========================================

{{subnetResources}}

# ========================================
# Outputs
# ========================================

output "vcn_id" {
  description = "OCID of the VCN"
  value       = oci_core_vcn.vcn.id
}

output "vcn_name" {
  description = "Name of the VCN"
  value       = oci_core_vcn.vcn.display_name
}

output "internet_gateway_id" {
  description = "OCID of the Internet Gateway"
  value       = oci_core_internet_gateway.igw.id
}

output "route_table_id" {
  description = "OCID of the Route Table"
  value       = oci_core_route_table.rt.id
}

output "security_list_id" {
  description = "OCID of the Security List"
  value       = oci_core_security_list.sl.id
}

{{subnetOutputs}}
