#!/bin/bash
# AWS CLI Script to Create VPC and Subnets
# Generated by ipcalc.cloud

# ========================================
# Variables
# ========================================
PREFIX="myproject"
REGION="us-east-1"
VPC_CIDR="{{vpcCidr}}"

{{subnetVariables}}

# ========================================
# Create VPC
# ========================================
echo "Creating VPC..."
VPC_ID=$(aws ec2 create-vpc \
  --cidr-block "${VPC_CIDR}" \
  --region "${REGION}" \
  --tag-specifications "ResourceType=vpc,Tags=[{Key=Name,Value=${PREFIX}-vpc}]" \
  --query 'Vpc.VpcId' \
  --output text)

echo "VPC ID: ${VPC_ID}"

# ========================================
# Create Subnets
# ========================================
{{subnetCreation}}

echo "AWS VPC and Subnets created successfully!"
