# Terraform Configuration for AWS VPC and Subnets
# Generated by ipcalc.cloud

# ========================================
# Provider Configuration
# ========================================

terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
  }
}

provider "aws" {
  region = var.region
}

# ========================================
# Variables
# ========================================

variable "prefix" {
  description = "Prefix for resource naming"
  type        = string
  default     = "myproject"
}

variable "region" {
  description = "AWS region for resources"
  type        = string
  default     = "us-east-1"
}

variable "vpc_cidr" {
  description = "CIDR block for the VPC"
  type        = string
  default     = "{{vpcCidr}}"
}

{{subnetVariables}}

# ========================================
# VPC
# ========================================

resource "aws_vpc" "main" {
  cidr_block           = var.vpc_cidr
  enable_dns_hostnames = true
  enable_dns_support   = true

  tags = {
    Name        = "${var.prefix}-vpc"
    Environment = "Production"
    ManagedBy   = "Terraform"
  }
}

# ========================================
# Subnets
# ========================================

{{subnetResources}}

# ========================================
# Outputs
# ========================================

output "vpc_id" {
  description = "ID of the VPC"
  value       = aws_vpc.main.id
}

{{subnetOutputs}}
